version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    working_dir: '/opt/job_research'
    tty: true
    volumes:
      - /Users/taipon512/develop/job_research:/opt/job_research