version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "13306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: shiba30db
      MYSQL_USER: shiba30
      MYSQL_PASSWORD: shiba30pass
      MYSQL_ROOT_PASSWORD: passwordss
volumes:
    db_data: